### ISSUE TITLE
Bot currently unable to handle excessive volume of YouTube API calls to add playlist items.

### ISSUE THREAD

**Issue by swoocn** [swoocn/youtube-request-twitch-bot#2]
Upon load testing; 45/70 requests make it to the playlist.  Those that failed are logged as follows..

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at addToPlaylist (C:\Users\swoos\Documents\Freelancer\Danny\Projects\youtube_request_twitch_bot\src\quickstart.js:128:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 28)
```

**Comment by swoocn** [comment]
May be considered as an enhancement since current bot state is unable to handle extreme frequency and volume; plan to utilize some sort of queue implementation, i.e., Cloud tasks.  Though, reminder that GCP incurs resource costs after free trial.
